### ISSUE TITLE
Move to internal

### ISSUE THREAD

**Issue by matt-may** [gatech-cse6242/flask-backend#1]
@StefanoFenu Hey, I am going to create us a private repo on github.gatech.edu with this. I'll initialize it over there. Let me know when I can remove this one?

**Comment by matt-may** [comment]
It is now up at https://github.gatech.edu/gatech-cse6242/flask-backend

**Comment by StefanoFenu** [comment]
Ok, you can feel free to remove the public one.

**Comment by matt-may** [comment]
Ok, great!
